added OnHeap Downsampled segment
OpenTSDB/opentsdb-aura pull request #13
Opened 2021-08-10 00:14 UTC by smrutilal2

2021-08-10 16:59 UTC, manolama reviewed
moar UTs would help

2021-10-04 23:06 UTC, manolama requested changes

2021-10-04 23:06 UTC, manolama commented on opentsdb/src/main/java/net/opentsdb/aura/metrics/storage/AerospikeBatchQueryNode.java
> +                          if (dsInterval < rollupInterval) {
And we need a validation that the rollup interval is a multiple of the source interval. E.g. if they give us a 67 second downsample we should throw.

2021-10-05 04:44 UTC, smrutilal2 commented on core/src/main/java/net/opentsdb/aura/metrics/core/gorilla/AerospikeDSTimeSeriesEncoder.java
> +      Arrays.fill(valueBuffer, Double.NaN);
In case, it's an empty segment, it fills the array with nans and return. Otherwise, the decoder will do the filling appropriately.

2021-10-05 05:43 UTC, smrutilal2 commented on aerospike/src/main/java/net/opentsdb/aura/metrics/AerospikeDSTimeSeriesEncoder.java
> +      }
`this.aggId == segment.getAggs()`. But, it's confusing now. I will re do it.

2021-10-07 17:16 UTC, merged